/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as MapRouteImport } from './routes/map'
import { Route as LocationSlugRouteImport } from './routes/location.$slug'
import { Route as LocationSlugDiscussionsRouteImport } from './routes/location.$slug.discussions'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationSlugRoute = LocationSlugRouteImport.update({
  id: '/location/$slug',
  path: '/location/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationSlugDiscussionsRoute = LocationSlugDiscussionsRouteImport.update({
  id: '/discussions',
  path: '/discussions',
  getParentRoute: () => LocationSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/explore': typeof ExploreRoute
  '/map': typeof MapRoute
  '/location/$slug': typeof LocationSlugRouteWithChildren
  '/location/$slug/discussions': typeof LocationSlugDiscussionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/explore': typeof ExploreRoute
  '/map': typeof MapRoute
  '/location/$slug': typeof LocationSlugRouteWithChildren
  '/location/$slug/discussions': typeof LocationSlugDiscussionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/explore': typeof ExploreRoute
  '/map': typeof MapRoute
  '/location/$slug': typeof LocationSlugRouteWithChildren
  '/location/$slug/discussions': typeof LocationSlugDiscussionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/explore'
    | '/map'
    | '/location/$slug'
    | '/location/$slug/discussions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/explore'
    | '/map'
    | '/location/$slug'
    | '/location/$slug/discussions'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/auth'
    | '/explore'
    | '/map'
    | '/location/$slug'
    | '/location/$slug/discussions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ExploreRoute: typeof ExploreRoute
  MapRoute: typeof MapRoute
  LocationSlugRoute: typeof LocationSlugRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/location/$slug': {
      id: '/location/$slug'
      path: '/location/$slug'
      fullPath: '/location/$slug'
      preLoaderRoute: typeof LocationSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/location/$slug/discussions': {
      id: '/location/$slug/discussions'
      path: '/discussions'
      fullPath: '/location/$slug/discussions'
      preLoaderRoute: typeof LocationSlugDiscussionsRouteImport
      parentRoute: typeof LocationSlugRoute
    }
  }
}

interface LocationSlugRouteChildren {
  LocationSlugDiscussionsRoute: typeof LocationSlugDiscussionsRoute
}

const LocationSlugRouteChildren: LocationSlugRouteChildren = {
  LocationSlugDiscussionsRoute: LocationSlugDiscussionsRoute,
}

const LocationSlugRouteWithChildren = LocationSlugRoute._addFileChildren(
  LocationSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ExploreRoute: ExploreRoute,
  MapRoute: MapRoute,
  LocationSlugRoute: LocationSlugRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
